# Site settings
author: Reno Neto
title: Reno Neto
header-img: img/home-bg.png
email: renoneto@gmail.com
copyright_name: Reno Neto
description: > # this means to ignore newlines until "baseurl:"
  import data-scientist as renoneto
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  renoneto

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
